# Generated by Django 4.2 on 2023-05-31 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='major',
            options={'verbose_name': 'تخصص', 'verbose_name_plural': 'تخصص ها'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'یگان', 'verbose_name_plural': 'یگان ها'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'شخص', 'verbose_name_plural': 'اشخاص'},
        ),
        migrations.AlterModelOptions(
            name='subjectrecord',
            options={'verbose_name': 'گزارش مربوط به شخص', 'verbose_name_plural': 'گزارشات مربوط به اشخاص'},
        ),
        migrations.AddField(
            model_name='subject',
            name='serve_place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.place', verbose_name='محل خدمت'),
            preserve_default=False,
        ),
    ]
