# Generated by Django 4.2 on 2023-05-31 19:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_major_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectrecord',
            name='time',
            field=models.PositiveSmallIntegerField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], default=core.models.get_this_jalali_month_index),
        ),
    ]
